### ISSUE TITLE
Add support for thread script attributes

### ISSUE THREAD

**Issue by mjhagen** [jcberquist/sublimetext-cfml#10]
The `thread` keyword in cfscript should be handled the same way as the `lock` keyword. Right now, it doesn't auto complete the attributes.

**Comment by jcberquist** [comment]
Good catch. I have a list of language "scopes" that is searched before the tag in script section; it is as follows:
```
application|arguments|attributes|caller|cgi|client|cookie|flash|form|
local|request|server|session|thistag|thread|thread local|url|variables|
self|argumentcollection
```
So `thread` is getting matched as a scope, and never as a tag, though it is in the list of tags :/ I should probably review that list - I can't remember now where I got it from, but at least `thread local` doesn't make sense to me now. I think that is just the scope where "unscoped" vars used in a thread go? Anyways, I don't think it should be here.

I suppose the easiest fix for this is to check if `thread` is followed immediately by a `.` and mark it as a scope in that case, but otherwise mark it as a tag.
