### ISSUE TITLE
Error on install

### ISSUE THREAD

**Issue by kilroy59** [jcberquist/sublimetext-cfml#114]
Hello,

Just installed cfml through package control, restart and when i load a cf file I get this error:

error: Error loading syntax file "Packages/CFML/syntaxes/cfml.sublime-syntax": Apparent recursion within a with_prototype action: 25000 context sanity limit hit

Any idea whats going on?

Thank You

**Comment by kilroy59** [comment]
OK,

Figured out the conflict. Uninstalled 'ultimate Javascript' and it works.

**Comment by jeffjones72** [comment]
For me, it was conflicts with other packages.  I had to remove other packages one by one.

Also needed to recreate any sublime projects.

**Comment by jcberquist** [comment]
Glad you figured it out. This does seem to be a recurring problem. The JavaScript include is actually via the included default HTML syntax, so I don't have direct control over it - if a third party JavaScript syntax overrides the default syntax there will always be the potential for this to happen.

That said I think most third party JS syntaxes will work, and the situation is definitely better in the dev builds, where the method of including the JavaScript and CSS syntaxes in HTML has been improved. (Because of this when the next beta build comes out people should see a significant improvement for initial load times of CFML files after startup.)  I can install JavaScript Ultimate on a dev build and it works with the CFML package - though it is a huge syntax file and I am a bit surprised that it can survive being included.
