### ISSUE TITLE
Add multi-colored curly brackets

### ISSUE THREAD

**Issue by redtopia** [jcberquist/sublimetext-cfml#124]
I just saw a screenshot of this feature in an ms code plugin and it seems like an amazing feature! Makes it easy to visually identify ends of your blocks.

**Comment by jcberquist** [comment]
This sounds interesting, but I don't think it is something I would implement in this package. 

I think it is possible to give brackets/braces distinct colors by using the `add_regions` feature of the sublime View class, but it would be a bit hacky since the view regions are not really there to modify color schemes. I found a package [Rainbowth](https://packagecontrol.io/packages/Rainbowth) that does this - though it looks to me to be a bit out of date in terms of how it handles color schemes.

Other approaches: I presume you have already tried a package like [BracketHighlighter](https://packagecontrol.io/packages/BracketHighlighter)? You might also try looking at the section on brackets in the color scheme documentation:
https://www.sublimetext.com/docs/3/color_schemes.html#global_settings-brackets
It is easy with the latest builds of ST3 to override parts of color schemes without replacing all of them, so you could update just the bracket settings of your color scheme to make the matching bracket highlighting used in ST by default more visible.

**Comment by redtopia** [comment]
Thanks for considering it... yea, I can see how this is outside of the scope of a cfml plugin. Thanks for the links.
