### ISSUE TITLE
ST4 4175 and SQL Code Highlighting

### ISSUE THREAD

**Issue by ivanionut** [jcberquist/sublimetext-cfml#148]
In version ST4 4175, SQL code is no longer highlighted correctly:

![sql](https://github.com/jcberquist/sublimetext-cfml/assets/2210744/4be31dda-ac0c-4041-bb00-6445bfc5c4de)

In the [**ST4 DEV changelog**](https://www.sublimetext.com/dev), I found two builds (4174 and 4175) with the note "_Various syntax highlighting improvements_."

**Comment by jcberquist** [comment]
I have tested this, and it looks like the SQL highlighting scopes are still being applied (e.g. `source.sql keyword.other.DML.sql` for the `SELECT`). If you are not seeing distinctive highlighting for those scopes it might be because of how your color scheme is highlighting those scopes.

You can verify the scopes applied to the SQL yourself by placing your cursor in the SQL statement and running the `show_scope_name` command. On Windows that is bound by default like so:
```
{ "keys": ["ctrl+alt+shift+p"], "command": "show_scope_name" }
```
