### ISSUE TITLE
Turning on cfml_auto_insert_closing_tag throws an error on typing `>`

### ISSUE THREAD

**Issue by mjhagen** [jcberquist/sublimetext-cfml#2]
I created a new file, typed: `<cfoutput` and couldn't type `>`. I checked the console where this message is shown:

```
Traceback (most recent call last):
  File "{path-to}\Sublime Text 3\sublime_plugin.py", line 556, in run_
    return self.run(edit)
  File "cfml_plugin in {path-to}\Sublime Text 3\Data\Installed Packages\CFML.sublime-package", line 72, in run
AttributeError: 'module' object has no attribute 'get_next_character'
```

`"cfml_auto_insert_closing_tag":false` throws no error.

(This is using the Package Control version)

**Comment by mjhagen** [comment]
Using a clean install I don't get the error, so it might be a conflict with some other package/setting. I'll investigate further.

**Comment by mjhagen** [comment]
I suspect it has something to do with the Package Control update mechanism, since after a restart of ST and reinstall of all my installed packages the error went away. I checked the installed packages at the time of the error against the latest versions and there were no differences.

I'll close the issue for now.

**Comment by jcberquist** [comment]
While Sublime Text 3 will reload python code in the main folder of a package whenever that code changes, it only imports python files in package sub folders when it initially starts up. Your trace tells the tale - the plugin can't find a new function I added to the `src/utils.py` module, and it won't until ST is restarted.

I am sorry, I knew this was an issue, and I was going to add a note to the update message telling people that they would need to restart ST after the update, but I forgot. I might add a patch release that just comes with a restart reminder. I need to add the same note to an install message anyways, since the same issue applies to an initial install of the package.

**Comment by mjhagen** [comment]
Yeah, I knew this and I usually restart sublime just to be sure, for some reason I didn't this time :/
