### ISSUE TITLE
queryExecute

### ISSUE THREAD

**Issue by ivanionut** [jcberquist/sublimetext-cfml#22]
Hi,
firstly, congratulations for the plugin!

You plan an implementation of `queryExecute`?  👍

**Comment by jcberquist** [comment]
Thank you! Could you be more explicit about what you mean by "an implementation of `queryExecute`"?

**Comment by ivanionut** [comment]
I'm sorry. I have been too brief...
I mean a coloration that is most similar to `new Query`
![query](https://hostr.co/file/wjZi1eM89a9f/query.png)

**Comment by jcberquist** [comment]
The colors come from the combination of the scopes assigned to the text by the CFML syntax and the color scheme you are using. (You can see the scopes assigned to a given character by placing the cursor there and pressing <kbd>CTRL</kbd>+<kbd>ALT</kbd>+<kbd>SHIFT</kbd>+<kbd>p</kbd> on Windows, or <kbd>CMD</kbd>+<kbd>ALT</kbd>+<kbd>p</kbd> on a Mac.) 

In this case, for example, when you have `value="USA"` in `queryExecute` it is a struct key value pair, and the scope `value` currently gets is `meta.struct-literal.key.cfml`. Typically, most color schemes don't assign colors directly to meta scopes. Whereas in the query.cfc example, where you have `value = "USA"`, `value` currently gets the scope `entity.other.method-parameter.cfml`. This is why the colors are different. You can always edit your color scheme to add or change the colors assigned to scopes.

I should warn you in this case that I will probably be changing `entity.other.method-parameter.cfml` to `variable.parameter.cfml` in order to stay in sync with the scopes being assigned in the official ST syntaxes.

**Comment by ivanionut** [comment]
ok, thank you for your patience and for your explanation!
