### ISSUE TITLE
cfscript formatter: Lucee bug 611

### ISSUE THREAD

**Issue by mjhagen** [jcberquist/sublimetext-cfml#38]
I suddenly remembered there's a bug in Lucee regarding the `param` syntax. It errors when you have spaces surrounding the '='-sign. So it might be a good idea to either not format that syntax or make an exception for it. Until that bug is fixed.

Bug detailed here: https://luceeserver.atlassian.net/browse/LDEV-611

**Comment by jcberquist** [comment]
Interesting, I didn't know about that; what a strange bug. That said, were you finding that the cfscript formatter was formatting the `=` in a param? I don't think it will currently, since I have `=` scoped differently for tag attributes than when it is used as an assignment operator.

**Comment by mjhagen** [comment]
I haven't tested / didn't run into it, it just occurred to me that that bug might be a problem for a code formatter and thought I'd at least wright it down somewhere :) if it doesn't touch the `=` anyway than maybe just close this issue?

**Comment by jcberquist** [comment]
I think I will close it for now because I know it isn't currently an issue.

That said, though I probably won't get to it in the near future, down the road I would like to add formatting for tags-in-script as well as params, properties and component attributes. If/when I do that I don't want to forget this.
