### ISSUE TITLE
closing > under Linux

### ISSUE THREAD

**Issue by byandrewdavis** [jcberquist/sublimetext-cfml#42]
I'm having a problem with being about to complete a tag such as <cfoutput></cfoutput>
I'm unable to type the **>**

i wonder if this may have something to do with it (mappings, etc.)
I am running ubuntu in parallels with a mac keyboard. 

I can switch to HTML or any other in the bottom right and it allows me to type it.

**Comment by jcberquist** [comment]
I am sorry you are having trouble. Have you looked at this issue: https://github.com/jcberquist/sublimetext-cfml/issues/34?

In order to debug this it would be helpful to know:
- what version of the package you are using?
- did you download/git clone it to install, or did you use Package Control?
- if you didn't use Package Control, what parent folder did you put it in, and what did you name it?
- if you close ST and then reopen it and look at the console do you see any errors reported there?
- if you run `sublime.log_commands(True)` from the console, and then try typing a `>` to complete a tag in a view, what, if anything, is printed to the console?

I think the other cases were caused by an issue where this package wasn't loading properly, so while the correct command was being run when `>` was pressed, the command wasn't executing properly.

**Comment by byandrewdavis** [comment]
Thank you, reinstalling via package control did the trick.
