### ISSUE TITLE
Can't get custom tag insight to work

### ISSUE THREAD

**Issue by gruskada** [jcberquist/sublimetext-cfml#53]
I edited the project file with the following:

```
{
    "folders": [{"path": "C:\\cfmx"}],
    "custom_tag_folders": [{
            "path": "c:\\cfmx\\customtags",
            "prefix": "page"
    }]
}
```

and then added the following code to a .cfm page:

```
<cfimport prefix="page" taglib="c:\cfmx\customtags">
<page:
```

After I type the ":", I get a list of all the built-in CF tags only. I tried using a relative path, and restarting, with no luck.

Do I need to do anything else to set this up?

Thanks.

**Comment by jcberquist** [comment]
Your setup looks correct to me. Could you try looking in the Sublime Text console to see if there are any errors? Also, when this is properly indexing custom tag files you should see the following lines in your console output:
```
CFML: indexing custom tags in project '/path/to/project_file.sublime-project'
CFML: indexing custom tags in project '/path/to/project_file.sublime-project' completed - x files indexed in y seconds
```

**Comment by jcberquist** [comment]
Glad you got it working. Thanks for sharing your console output. It looks to me like there are a number of errors there. The significant one for this issue is that the file read on the custom tag file (that you ended up removing) failed. I don't gracefully handle that as I should, so, though I catch the read error and output the console message you see:
```
CFML: unable to read file - c:/cfmx/customtags/test.cfm
```
it is then followed immediately by the key error (`tag_name`). That is why none of the tags were showing up. I will get that fixed so it doesn't cause a total failure when a single file can't be read. 

There must be a character (or characters) in the file that can't be read by Python when specifying `utf-8` encoding for the file read (see [here](https://github.com/jcberquist/sublimetext-cfml/blob/master/src/custom_tags/custom_tag_index.py#L20-L21)). I think the message at the bottom of the console confirms this, as it is a ST message saying that it can't figure out the encoding in that  same file so it is falling back to your Windows system default. I am not sure about trying to sort out why Python can't read it, since I don't really want to get more complex in the file reads than specifying `utf-8`. So I think my focus will be on ensuring the read failure is logged, and that it doesn't cause a total failure.

There is also another error in your log, that I was already aware of, but haven't gotten around to fixing. When files in indexed folders are saved I re-index them. I do it in an async thread, so as to not affect the ST UI. That typically works great, except for the particular situation where you close a file that has edits and ST asks if you want to save before closing. If you select yes, by the time the on save callback is invoked, the file is closed and the file information is lost. That results in the error you see:
```
AttributeError: 'NoneType' object has no attribute 'project_file_name'
```
I am still thinking about that one, so thanks for reminding me :)

**Comment by jcberquist** [comment]
For the time being, if a file is saved and closed, a warning will be printed to the console, and no error thrown.
