### ISSUE TITLE
Autocompletions  from local buffer are not working in CFCs

### ISSUE THREAD

**Issue by jtreher** [jcberquist/sublimetext-cfml#57]
We are using 0.19 and ST3 3126. Code completion from the local buffer is not working. It appears that all the CFML completions are working, but something is preventing the local buffer options from coming up. I've verified this on multiple developer machines and with a fresh install of the portable version.

The work around is that you must scope your variable to get the CFML plugin to handle completion ( I think that's what it's doing ), but the sublime default local buffer should still be kicking in.

```
component{
	workshop = true;

	public function init(){
		var foobarit = "bar";
		bar = foob // will not autocomplete unless you use local.
                variables.work // will autocomplete because it is scoped
                .foobar // oddly enough foobarit will be an option here with just a single dot

	}

}
```

**Comment by jcberquist** [comment]
Thanks for reporting this. I hadn't noticed this myself because I use the AllAutocomplete plugin, but after disabling it I see the same behavior. I am not sure what is causing it at this point, I will try to dig around.

**Comment by jtreher** [comment]
@jcberquist No problem. At this point, I'm guessing that it's not at all a matter of "scoping" but it's requiring a period before being willing to search the local buffer.

**Comment by jtreher** [comment]
Confirmed that allautocomplete is the most sane workaround.

**Comment by jcberquist** [comment]
So I have done a little digging on this, and it seems that the issue is that the method completions I include in components include parentheses (see `init()` below):

![image](https://cloud.githubusercontent.com/assets/3498220/20252295/e14110a6-a9ee-11e6-90c1-1e39774e5adf.png)

But the parentheses are word separators by default in ST (nor do I think one would want to change that), and that seems to stop ST from including its own completions. If I either remove the parentheses from the completion, or remove parentheses from the list of word separators ST uses (`word_separators` in the ST preferences file), then the local buffer completions start working again.

So I think the solution to this might be rearranging how the completions are displayed so only the method name is on the left of the completions list, and on the right where it now has _`this`_ I add the method name (and return type, where applicable). So on the right you would get _`this.init()`_ or maybe _`this.init():any`_. Any thoughts?

**Comment by jcberquist** [comment]
With version 0.20.0, one can either go with simple completion names, which won't block ST, or use the full completion name `method():returntype` and then use something such as `All Autocomplete` to get local buffer completions back.
