### ISSUE TITLE
Installing package

### ISSUE THREAD

**Issue by eric00000007** [jcberquist/sublimetext-cfml#69]
I just updated the package and I have an issue on Windows
Error loading syntax file

> "Packages/sublimetext-cfml-master/syntaxes/cfml.sublime-syntax":
> Unable to read Packages/sublimetext-cfml-master/syntaxes/cfml.sublime-syntax

**Comment by jcberquist** [comment]
Is this still an issue for you? I ask because you were clearly able to test things out in ST after you posted this issue.

**Comment by eric00000007** [comment]
It happend when I just installed a fresh Sublime text 3 and the package with a git clone. I tried several times to install the package with Git clone, with Package Control Install and with the Zip file downloaded. I have this issue all the time. In one install I copy the cfml.sublim syntax from a previous install.

**Comment by eric00000007** [comment]
forget the issue with the error Error loading syntax file. It happend when I change the package folder and when a file isalready open and use the previous package... 

now I have something `shift + alt + f` does not work but `shift + ctrl +p +indentation: Reindent Lines` works .... certainly an issue with some settings on Sublime Text 3

**Comment by jcberquist** [comment]
Ok, I am going to close this since you sorted out the original issue.

Regarding the key binding <kbd>SHIFT</kbd>+<kbd>ALT</kbd>+<kbd>F</kbd> is not bound to any command by default on Windows. In the CFML package I do use that key binding for a formatting command, but that does not include any tag formatting. Possibly you had that key binding mapped to the reindent command in a user key binding file in your old install?

**Comment by eric00000007** [comment]
yes exactly, I forgot this detail. I added a key binding in the user sublime keymap
`{"keys": ["alt+shift+f"], "command": "reindent", "args": {"single_line": false}}`
I have to read more about the difference between formatting command and reindent
