### ISSUE TITLE
Right Caret breaks string formatting

### ISSUE THREAD

**Issue by ekbarber** [jcberquist/sublimetext-cfml#86]
I just noticed that if you have a Right Caret (>) in a string, it breaks the formatting for the string. 

![image](https://user-images.githubusercontent.com/4382558/30486036-56c1739e-99fd-11e7-83f8-657476a1c18f.png)

**Comment by elpete** [comment]
That's not valid in tags, right? Doesn't that need to be `GTE`?

```
<cfset var testString = num1 GTE num2 />
```

**Comment by ekbarber** [comment]
@elpete Well this is within a string I'm talking about. For my specific use case it's a string containing part of a SQL statement, so having a ">" or "<" or any variation should certainly be valid.

**Comment by jcberquist** [comment]
@ekbarber: thanks, good catch. This situation is tricky for the way I have the cfscript syntax set up, because there I want match `>` as an operator continuing an expression. Combining that with the situation in CFML tags where it ends the tag is tricky. I can actually simplify my syntax a bit and get it to match your example as it should. 

Unfortunately that will mean that in a situation with nested expressions like the following:
```coldfusion
<cfset a = (b>c)>
```
It will no longer detect the first `>` as ending the tag (noting that that syntax is invalid and will cause ColdFusion to throw an error). The only way I see right now to correctly handle both situations is to duplicate large portions of the cfscript syntax, and I am not inclined to do that unless it is really necessary. 

I definitely want to fix the highlighting in strings, so I will get this fixed, and then I guess we will see if it causes other issues.
